# Generated by Django 3.1.7 on 2021-03-06 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='data',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
